apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: codefresh
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-01634da6-9eac-4a95-931b-28f4ecada939:
      events:
        - push
      repositories:
        - owner: danielm-codefresh
          names:
            - test-gs
      webhook:
        port: '80'
        method: POST
        endpoint: >-
          /webhooks/some-namespace/codefresh/github-01634da6-9eac-4a95-931b-28f4ecada939
        url: https://daniel-dev-nginx.pipeline-team.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: runtime-repo-creds-secret
        key: password
