apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: argo-hub.yarn
  annotations:
    argo-hub/description: 'Execute yarn operations'
    argo-hub/categories: 'registry,node'
    argo-hub/icon_url: "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@main/coming-soon/yarn/icon.svg"
    argo-hub/icon_background: "#f4f4f4"
spec:
  templates: []
