apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: codefresh-marketplace.argo-workflows.0.0.1
  annotations:
    codefresh-marketplace/version: '0.0.1'
    codefresh-marketplace/categories: 'argo'
    icon-type: svg
    icon-url: "https://cdn.jsdelivr.net/gh/codefresh-io/2.0-marketplace/argo-workflows/assets/argo.svg"
    icon-background: "#81D4FA"

spec:
  templates:
    - name: submit-workflow
      serviceAccountName: codefresh-marketplace.argo-workflows.0.0.1
      metadata:
        annotations:
          icon-type: svg
          icon-url: "https://cdn.jsdelivr.net/gh/codefresh-io/2.0-marketplace/argo-workflows/assets/argo.svg"
          icon-background: "#81D4FA"
      inputs:
        parameters:
          - name: TEMPLATE_NAME
          - name: ENTRYPOINT
          - name: GIT_REPO
          - name: GIT_REVISION
          - name: GIT_REVISION_SHORT
          - name: GIT_BRANCH
      container:
        name: main
        imagePullPolicy: Always
        image: argoproj/argocli
        command:
          - argo
          - submit
          - --from=wftmpl/{{ inputs.parameters.TEMPLATE_NAME }}
          - --entrypoint={{ inputs.parameters.ENTRYPOINT }}
          - -p=GIT_REPO={{ inputs.parameters.GIT_REPO }}
          - -p=GIT_REVISION={{ inputs.parameters.GIT_REVISION }}
          - -p=GIT_REVISION_SHORT={{ inputs.parameters.GIT_REVISION_SHORT }}
          - -p=GIT_BRANCH={{ inputs.parameters.GIT_BRANCH }}
          - -l=git-revision={{ inputs.parameters.GIT_REVISION }},git-branch={{ inputs.parameters.GIT_BRANCH }},workflow-template-name={{ inputs.parameters.TEMPLATE_NAME }}
