apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: argo-hub.upgrade-cluster.0.0.1
  annotations:
    argo-hub/version: '0.0.1'
    argo-hub/description: 'This Workflow Template is used to upgrade a GitOps Runtime'
    argo-hub/categories: 'Administration'
    argo-hub/license: 'MIT'
    argo-hub/owner_name: 'Laurent Rochette'
    argo-hub/owner_email: 'laurent.rochette@codefresh.io'
    argo-hub/owner_avatar: 'https://avatars.githubusercontent.com/lrochette'
    argo-hub/owner_url: 'https://github.com/lrochette'
    argo-hub/icon_url: "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@main/examples/upgrade-cluster/assets/icon.svg"
    argo-hub/icon-background: "#004C76"
spec:
  entrypoint: upgrade
  templates:
    - name: upgrade
      metadata:
        annotations:
          argo-hub-template/description: 'Upgrade a runtime'
          argo-hub-template/icon_url: "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@main/workflows/upgrade-cluster/assets/icon.svg"
          argo-hub-template/icon_background: "#004C76"
      inputs:
        parameters:
          - name: RUNTIME_NAME
      dag:
        tasks:
          # https://codefresh.io/argohub/workflow-template/kaniko
          - name: upgrade
            template: freestyle
            arguments:
              parameters:
                - name: image
                  value: 'quay.io/codefresh/cli-v2'
                - name: commands
                  value: 'cf upgrade {{ inputs.parameters.RUNTIME_NAME }}'
                - name: shell
                  value: 'bash'

    # Test template
    - name: freestyle
      metadata:
        annotations:
          argo-hub-template/description: 'Run any command on any image'
          argo-hub-template/icon_url: "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@main/workflows/freestyle/assets/icon.svg"
          argo-hub-template/icon_background: "#004C76"
      inputs:
        parameters:
          - name: image
          - name: commands
          - name: working_directory
            value: ./
          - name: shell
            value: sh

      script:
        image: "{{ inputs.parameters.image }}"
        command: ["{{ inputs.parameters.shell }}"]
        source: |
          cd {{ inputs.parameters.working_directory }}
          echo Executing commands:
          {{inputs.parameters.commands}}
