apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: argo-hub.webhook
  annotations:
    argo-hub/description: 'Execute generic webhooks'
    argo-hub/categories: 'webhook'
    argo-hub/icon_url: "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@main/coming-soon/webhook/icon.svg"
    argo-hub/icon_background: "#f4f4f4"
spec:
  templates: []
