apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: codefresh-marketplace.codefresh-classic.0.0.1
  annotations:
    codefresh-marketplace/version: '0.0.1'
    codefresh-marketplace/categories: 'argo'
    icon-type: svg
    icon-url: "https://cdn.jsdelivr.net/gh/codefresh-io/2.0-marketplace/workflows/codefresh-classic/assets/icon.svg"
    icon-background: "#81D4FA"

spec:
  templates:
    - name: run-pipeline
      serviceAccountName: codefresh-marketplace.codefresh-classic.0.0.1
      metadata:
        annotations:
          icon-type: svg
          icon-url: "https://cdn.jsdelivr.net/gh/codefresh-io/2.0-marketplace/utils/codefresh-classic/assets/icon.svg"
          icon-background: "#81D4FA"
      inputs:
        parameters:
          - name: CF_API_KEY_SECRET
          - name: PIPELINE_NAME
          - name: TRIGGER_NAME
          - name: CF_BRANCH
          - name: EXTRA_OPTIONS
            default: ''
          - name: VARIABLES
            default: ''
      script:
        name: main
        imagePullPolicy: Always
        image: codefresh/cli
        env:
          - name: VARIABLES
            value: '{{ inputs.parameters.VARIABLES }}'
          - name: CF_API_KEY
            valueFrom:
              secretKeyRef:
                name: '{{ inputs.parameters.CF_API_KEY_SECRET }}'
                key: token
        command: [sh]
        source: |
          codefresh \
          run \
          '{{ inputs.parameters.PIPELINE_NAME }}' \
          '-b={{ inputs.parameters.CF_BRANCH }}' \
          '-t={{ inputs.parameters.TRIGGER_NAME }}' \
          $(echo $VARIABLES | sed 's/,/ /g' | sed -E 's/(^|[ ])/ -v /g') \
          '{{ inputs.parameters.EXTRA_OPTIONS }}'

---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: codefresh-marketplace.codefresh-classic-mock.0.0.1
  annotations:
    codefresh-marketplace/version: '0.0.1'
    codefresh-marketplace/categories: 'argo'
    icon-type: svg
    icon-url: "https://cdn.jsdelivr.net/gh/codefresh-io/2.0-marketplace/workflows/codefresh-classic/assets/icon.svg"
    icon-background: "#81D4FA"
spec:
  entrypoint: main
  templates:
    - name: run-pipeline
      inputs:
        parameters:
          - name: CF_API_KEY_SECRET
          - name: PIPELINE_NAME
          - name: TRIGGER_NAME
          - name: CF_BRANCH
          - name: EXTRA_OPTIONS
            default: ''
          - name: VARIABLES
            default: ''
      dag:
        tasks:
          - name: mock
            templateRef:
              name: codefresh-marketplace.argo-workflows-utils.0.0.1
              template: echo
            arguments:
              parameters:
                - name: TEXT
                  value: '{{ inputs.parameters }}'
