apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: codefresh-marketplace.slack.0.0.1
  annotations:
    codefresh-marketplace/version: '0.0.1'
    codefresh-marketplace/categories: 'argo'
    icon-type: svg
    icon-url: "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@new_struct/workflows/slack/assets/icon.svg"
    icon-background: "#81D4FA"

spec:
  templates:
    - name: send-message
      serviceAccountName: codefresh-marketplace.slack.0.0.1
      metadata:
        annotations:
          icon-type: svg
          icon-url: "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@new_struct/workflows/slack/assets/icon.svg"
          icon-background: "#81D4FA"
      retryStrategy:
        limit: "10"
        retryPolicy: "Always"
        backoff:
          duration: "5s"
      inputs:
        parameters:
          - name: MODE
            value: "simple"
          - name: SLACK_HOOK_URL
          - name: SLACK_TEXT
      container:
        name: main
        imagePullPolicy: Always
        image: quay.io/codefreshplugins/v2-slack-notifier:main
        command:
          - node
          - /app/index.js
        env:
          - name: MODE
            value: '{{ inputs.parameters.MODE }}'
          - name: SLACK_HOOK_URL
            value: '{{ inputs.parameters.SLACK_HOOK_URL }}'
          - name: SLACK_TEXT
            value: '{{ inputs.parameters.SLACK_TEXT }}'
