apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: argo-hub.datree.0.0.1
  annotations:
    argo-hub/version: '0.0.1'
    argo-hub/description: 'Datree template'
    argo-hub/categories: 'utilities'
    argo-hub/license: 'MIT'
    argo-hub/owner_name: 'Matthew Chung'
    argo-hub/owner_email: 'matthew.chung@codefresh.io'
    argo-hub/owner_avatar: 'https://github.com/matthewchungcodefresh.png'
    argo-hub/owner_url: 'https://github.com/matthewchungcodefresh'
    argo-hub/icon_url: "https://github.com/codefresh-io/argo-hub@main/workflows/datree/assets/icon.svg"
    argo-hub/icon-background: "#f4f4f4"
spec:
  templates:
    - name: datree-policy-check
      serviceAccountName: argo-hub.datree.0.0.1
      metadata:
        annotations:
          argo-hub-template/description: 'This action runs the Datree CLI against given k8s configuration file/s in your repository, featuring full Helm and Kustomize support.'
          argo-hub-template/icon_url: "https://github.com/codefresh-io/argo-hub@main/workflows/datree/assets/icon.svg"
          argo-hub-template/icon_background: "#f4f4f4"
      retryStrategy:
        limit: "3"
        retryPolicy: "Always"
        backoff:
          duration: "5s"
      inputs:
        parameters:
          # required
          - name: DATREE_TOKEN
          - name: DATREE_TOKEN_SECRET_KEY
          - name: INPUT_PATH
          # optional
          - name: CLI_ARGUMENTS
            default: 
          - name: HELM_ARGUMENTS
            default: 
          - name: IS_HELM_CHART
            default: 
          - name: IS_KUSTOMIZATION
            default: 
          - name: KUSTOMIZE_ARGUMENTS
            default: 
          - name: WORKING_DIRECTORY
            default: 
      container:
        name: main
        imagePullPolicy: Always
        image: quay.io/codefreshplugins/argo-hub-workflows-datree-versions-0.0.1-images-datree-manager:main
        command:
          - python
          - /jira/jira_issue_manager.py
        env:
          - name: JIRA_BASE_URL
            value: '{{ inputs.parameters.JIRA_BASE_URL }}'
          - name: JIRA_USERNAME
            valueFrom:
              secretKeyRef:
                name: '{{ inputs.parameters.JIRA_USERNAME }}'
                key: '{{ inputs.parameters.JIRA_USERNAME_SECRET_KEY }}'
          - name: JIRA_API_KEY
            valueFrom:
              secretKeyRef:
                name: '{{ inputs.parameters.JIRA_API_KEY }}'
                key: '{{ inputs.parameters.JIRA_API_KEY_SECRET_KEY }}'
          - name: ACTION
            value: 'comment_create'
          - name: COMMENT_BODY
            value: '{{ inputs.parameters.COMMENT_BODY }}'
          - name: JIRA_ISSUE_SOURCE_FIELD
            value: '{{ inputs.parameters.JIRA_ISSUE_SOURCE_FIELD }}'