apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: testing-2
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-9c468c28-edf0-43fd-9597-4ef9ca76b18e
      eventName: github-9c468c28-edf0-43fd-9597-4ef9ca76b18e
      eventSourceName: testing-2
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
  triggers:
    - template:
        name: test
        conditions: github-9c468c28-edf0-43fd-9597-4ef9ca76b18e
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: testing-2-test-
              spec:
                workflowTemplateRef:
                  name: argo-hub.jira.0.0.1
          parameters: []
