apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: testing-2
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-9c468c28-edf0-43fd-9597-4ef9ca76b18e:
      events:
        - push
      repositories:
        - owner: matthewchungcodefresh
          names:
            - example-multiservice2
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/csdp/testing-2/github-9c468c28-edf0-43fd-9597-4ef9ca76b18e
        url: https://lrcsdp.support.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
