apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: codefresh-marketplace.argo-workflows-utils.0.0.1
  annotations:
    codefresh-marketplace/version: '0.0.1'
    codefresh-marketplace/categories: 'argo'
    icon-type: svg
    icon-url: "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@new_struct/workflows/argo-workflows-utils/assets/argo.svg"
    icon-background: "#81D4FA"

spec:
  templates:
    - name: echo
      serviceAccountName: codefresh-marketplace.argo-workflows-utils.0.0.1
      metadata:
        annotations:
          icon-type: svg
          icon-url: "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@new_struct/workflows/argo-workflows-utils/assets/argo.svg"
          icon-background: "#81D4FA"
      inputs:
        parameters:
          - name: TEXT
            default: 'default'
      container:
        name: main
        imagePullPolicy: Always
        image: alpine
        command: [echo]
        args: ["{{ inputs.parameters.TEXT }}"]

    - name: globalize-variable
      serviceAccountName: codefresh-marketplace.argo-workflows-utils.0.0.1
      metadata:
        annotations:
          icon-type: svg
          icon-url: "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@new_struct/workflows/argo-workflows-utils/assets/argo.svg"
          icon-background: "#81D4FA"
      inputs:
        parameters:
          - name: NAME
          - name: VALUE
      outputs:
        parameters:
          - name: VARIABLE
            value: '{{ inputs.parameters.VALUE }}'
            globalName: '{{ inputs.parameters.NAME }}'
      script:
        image: alpine
        command: [sh]
        source: |
          echo exposing new variable {{ inputs.parameters.NAME }}:{{ inputs.parameters.VALUE }}
