apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: argo-hub.argo-workflows-utils.0.0.1
  annotations:
    argo-hub/version: '0.0.1'
    argo-hub/description: 'Useful utils to enrich your argo workflow templates'
    argo-hub/license: 'MIT'
    argo-hub/owner_name: 'Vadim Gusev'
    argo-hub/owner_email: 'vadim.gusev@codefresh.io'
    argo-hub/owner_avatar: 'https://avatars.githubusercontent.com/u/77272973?v=4'
    argo-hub/owner_url: 'https://github.com/vadimgusev-codefresh'
    argo-hub/categories: 'argo'
    argo-hub/icon_url: "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@main/workflows/argo-workflows-utils/assets/icon.svg"
    argo-hub/icon_background: "#f4f4f4"
spec:
  templates:
    - name: echo
      metadata:
        annotations:
          argo-hub-template/description: 'Print some text'
          argo-hub-template/icon_url: "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@main/workflows/argo-workflows-utils/assets/icon.svg"
          argo-hub-template/icon_background: "#f4f4f4"
      inputs:
        parameters:
          - name: TEXT
            default: 'default'
      container:
        name: main
        imagePullPolicy: Always
        image: alpine
        command: [echo]
        args: ["{{ inputs.parameters.TEXT }}"]

    - name: globalize-variable
      metadata:
        annotations:
          argo-hub-template/description: 'Easily expose a new variable globally'
          argo-hub-template/icon_url: "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@main/workflows/argo-workflows-utils/assets/icon.svg"
          argo-hub-template/icon_background: "#f4f4f4"
      inputs:
        parameters:
          - name: NAME
          - name: VALUE
      outputs:
        parameters:
          - name: VARIABLE
            value: '{{ inputs.parameters.VALUE }}'
            globalName: '{{ inputs.parameters.NAME }}'
      script:
        image: alpine
        command: [sh]
        source: |
          echo exposing new variable {{ inputs.parameters.NAME }}:{{ inputs.parameters.VALUE }}
