apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: codefresh-marketplace.argo-workflows-utils.0.0.1
  annotations:
    codefresh-marketplace/version: '0.0.1'
    codefresh-marketplace/description: 'Useful utils to enrich your argo workflow templates'
    codefresh-marketplace/license: 'MIT'
    codefresh-marketplace/owner/name: 'Itai Gendler'
    codefresh-marketplace/owner/email: 'itai@codefresh.io'
    codefresh-marketplace/owner/avatar: 'https://avatars.githubusercontent.com/u/10414627?s=120&v=4'
    codefresh-marketplace/owner/url: 'https://github.com/itai-codefresh'
    codefresh-marketplace/categories: 'argo'
    codefresh-marketplace/icon/url: "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@new_struct/workflows/argo-workflows-utils/assets/icon.svg"
    codefresh-marketplace/icon/background: "#f4f4f4"
spec:
  templates:
    - name: echo
      serviceAccountName: codefresh-marketplace.argo-workflows-utils.0.0.1
      metadata:
        annotations:
          codefresh-marketplace/template/description: 'Print some text'
          codefresh-marketplace/template/icon/url: "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@new_struct/workflows/argo-workflows-utils/assets/icon.svg"
          codefresh-marketplace/template/icon/background: "#f4f4f4"
      inputs:
        parameters:
          - name: TEXT
            default: 'default'
      container:
        name: main
        imagePullPolicy: Always
        image: alpine
        command: [echo]
        args: ["{{ inputs.parameters.TEXT }}"]

    - name: globalize-variable
      serviceAccountName: codefresh-marketplace.argo-workflows-utils.0.0.1
      metadata:
        annotations:
          codefresh-marketplace/template/description: 'Easily expose a new variable globally'
          codefresh-marketplace/template/icon/url: "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@new_struct/workflows/argo-workflows-utils/assets/icon.svg"
          codefresh-marketplace/template/icon/background: "#f4f4f4"
      inputs:
        parameters:
          - name: NAME
          - name: VALUE
      outputs:
        parameters:
          - name: VARIABLE
            value: '{{ inputs.parameters.VALUE }}'
            globalName: '{{ inputs.parameters.NAME }}'
      script:
        image: alpine
        command: [sh]
        source: |
          echo exposing new variable {{ inputs.parameters.NAME }}:{{ inputs.parameters.VALUE }}
