apiVersion: v1
kind: ServiceAccount
metadata:
  name: codefresh-marketplace.starting-template.0.0.1
  annotations:
    codefresh-marketplace/version: '0.0.1'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: codefresh-marketplace.starting-template.0.0.1
  annotations:
    codefresh-marketplace/version: '0.0.1'
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - watch
      - patch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: codefresh-marketplace.starting-template.0.0.1
  annotations:
    codefresh-marketplace/version: '0.0.1'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: codefresh-marketplace.starting-template.0.0.1
subjects:
  - kind: ServiceAccount
    name: codefresh-marketplace.starting-template.0.0.1
