apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: sonar
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-2f1c7406-edbd-4f74-8bfd-55a8004cce21:
      events:
        - commit_comment
      repositories:
        - owner: matthewchungcodefresh
          names:
            - argo-hub
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/csdp/sonar/github-2f1c7406-edbd-4f74-8bfd-55a8004cce21
        url: https://lrcsdp.support.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
